# Generated by Django 2.2.3 on 2019-07-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190722_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='raiting',
            new_name='rating',
        ),
    ]
